name: Website
on:
  push:
    branch: [main]
jobs:
  deploy:
    name: Deploy files to Amazon S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Copy website files to AWS S3
        run: aws s3 sync src s3://www.mybytesni.com

      - name: Invalidate Caches
        run: aws cloudfront create-invalidation --distribution-id E1F56EPOZWRHDD --paths "/*"

